spring:
  profiles:
    active: db,core, admin
  messages:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    www.qingxiangyx.litemall.admin:  DEBUG
    www.qingxiangyx.litemall:  ERROR

swagger:
  production: false