package www.qingxiangyx.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import www.qingxiangyx.litemall.db.domain.SeckillOrder;
import www.qingxiangyx.litemall.db.domain.SeckillOrderExample;

public interface SeckillOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    long countByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int deleteByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int insert(SeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int insertSelective(SeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    SeckillOrder selectOneByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    SeckillOrder selectOneByExampleSelective(@Param("example") SeckillOrderExample example, @Param("selective") SeckillOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    List<SeckillOrder> selectByExampleSelective(@Param("example") SeckillOrderExample example, @Param("selective") SeckillOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    List<SeckillOrder> selectByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    SeckillOrder selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") SeckillOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    SeckillOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SeckillOrder record, @Param("example") SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SeckillOrder record, @Param("example") SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SeckillOrder record);
}